Support partial extension UID fetch.
yahoo/imapnio pull request #133
Opened 2022-10-25 17:13 UTC by nhant01

Support partial extension UID fetch.

2022-10-25 22:01 UTC, fansu commented on core/src/main/java/com/yahoo/imapnio/async/request/AbstractFetchCommand.java
> +                sb = new StringBuilder().append(ImapClientConstants.MINUS).append(partialExtUidFetchInfo.getLowestUid())
why do you create StringBuilder? you can directly do bb.writeBytes(...) to save memory.

2022-10-25 22:01 UTC, fansu commented on core/src/main/java/com/yahoo/imapnio/async/request/AbstractFetchCommand.java
> +            bb.writeBytes(sb.toString().getBytes(StandardCharsets.US_ASCII));
you do not need string builder, please directly write to ByteBuf

2022-10-25 22:28 UTC, fansu commented on core/src/main/java/com/yahoo/imapnio/async/request/AbstractFetchCommand.java
> +            bb.writeBytes(PARTIAL_EXTENSION_SP_B);
add SPACE and L_PAREN into PARTIAL_EXTENSION_SP_B as well, so no need to write these 3 lines

2022-10-25 22:33 UTC, fansu commented on core/src/main/java/com/yahoo/imapnio/async/request/UidFetchCommand.java
> +    public UidFetchCommand(@Nonnull final MessageNumberSet[] msgsets, @Nonnull final String items,
not critical but a pattern. Let's not let user to pass in @Nullable partialExtUidFetchInfo, a nullable value makes parameter list looks confusing (required or not required? such). Change this to @Nonnull instead, and let line 21 to call super(...)

2022-10-25 22:33 UTC, fansu commented on core/src/main/java/com/yahoo/imapnio/async/request/UidFetchCommand.java
> +    public UidFetchCommand(@Nonnull final MessageNumberSet[] msgsets, @Nonnull final FetchMacro macro,
not critical but a pattern. Let's not let user to pass in @Nullable partialExtUidFetchInfo, a nullable value makes parameter list looks confusing (required or not required? such). Change this to @Nonnull instead, and let line 21 to call super(...)

2022-10-25 22:34 UTC, fansu commented on core/src/main/java/com/yahoo/imapnio/async/request/UidFetchCommand.java
> +    public UidFetchCommand(@Nonnull final String uids, @Nonnull final String items,
not critical but a pattern. Let's not let user to pass in @Nullable partialExtUidFetchInfo, a nullable value makes parameter list looks confusing (required or not required? such). Change this to @Nonnull instead, and let line 65 to call super(...)

2022-10-25 22:34 UTC, fansu commented on core/src/main/java/com/yahoo/imapnio/async/request/UidFetchCommand.java
> +    public UidFetchCommand(@Nonnull final String uids, @Nonnull final FetchMacro macro,
not critical but a pattern. Let's not let user to pass in @Nullable partialExtUidFetchInfo, a nullable value makes parameter list looks confusing (required or not required? such). Change this to @Nonnull instead, and let line 87 to call super(...)

2022-10-25 22:35 UTC, fansu reviewed
Please check comments

2022-10-25 23:23 UTC, fansu approved these changes
looks good to me. @nvsnvikram please review

2022-10-26 00:16 UTC, fansu approved these changes

2022-10-26 19:26 UTC, nvsnvikram requested changes

2022-10-26 19:26 UTC, nvsnvikram commented on core/src/main/java/com/yahoo/imapnio/async/data/PartialExtensionUidFetchInfo.java
> +    public enum Range {
Can we remove range?

2022-10-26 23:59 UTC, fansu commented
looks good to me. 
reference rfc draft: https://datatracker.ietf.org/doc/draft-ietf-extra-imap-partial/

2022-10-27 02:31 UTC, nvsnvikram commented on core/src/main/java/com/yahoo/imapnio/async/data/PartialExtensionUidFetchInfo.java
> +    private final int lowestUid;
Fyi, range has only first & last. lowest:highest is equal to highest:lowest

2022-10-27 02:31 UTC, nvsnvikram approved these changes

2022-10-27 16:31 UTC, merged