ISSUE-147 isChannelClosed should be public
yahoo/imapnio pull request #148
Opened 2023-04-10 09:18 UTC by chibenwa

## Description

I would like to assert the state of a session before submitting requests to it.

## Motivation and Context

IMAP provisionning script

## How Has This Been Tested?

All tests passes

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Major release (change is NOT backward compatible with prior release)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2023-04-27 09:26 UTC, chibenwa commented
Hello @fansu 

What's the ETA of this?

2023-04-28 22:35 UTC, fansu commented on core/src/main/java/com/yahoo/imapnio/async/internal/ImapAsyncSessionImpl.java
> +    public boolean isChannelClosed() {
could you add unit test coverage for isChannelClosed in ImapAsyncSessionImplTest.java

2023-04-28 22:48 UTC, fansu requested changes
comments

2023-05-01 15:40 UTC, chibenwa commented
The last commit is an attempt to keep the test file below 2000 line of code and not trigger a checkstyle violation.

2023-05-01 21:22 UTC, fansu approved these changes

2023-05-01 21:22 UTC, merged